import React, { useState, useEffect } from 'react';
import { StyleSheet, Text, View, TextInput, TouchableOpacity, ScrollView, ActivityIndicator, Alert } from 'react-native';
import { useAuth } from '../context/AuthContext';
import { useTheme } from '../context/ThemeContext';
import { Smartphone, Check, X, ShieldAlert, KeyRound, ArrowLeft } from 'lucide-react-native';

export default function PushApproveScreen({ navigate, params }) {
  const { colors } = useTheme();
  const { respondToPushLogin } = useAuth();

  const [inputUrl, setInputUrl] = useState('');
  const [requestId, setRequestId] = useState(params?.requestId || '');
  const [token, setToken] = useState(params?.token || '');
  
  const [status, setStatus] = useState(params?.requestId && params?.token ? 'ready' : 'input'); // 'input' | 'ready' | 'loading' | 'approved' | 'denied' | 'error' | 'expired'
  const [error, setError] = useState('');
  const [countdown, setCountdown] = useState(120);

  // Set initial status if params changed
  useEffect(() => {
    if (params?.requestId && params?.token) {
      setRequestId(params.requestId);
      setToken(params.token);
      setStatus('ready');
      setCountdown(120);
    }
  }, [params]);

  // Parse pasted URL parameters automatically
  const handleParseUrl = () => {
    if (!inputUrl) {
      Alert.alert('Error', 'Please paste the approval link or scan code first.');
      return;
    }

    try {
      const cleanUrl = inputUrl.trim();
      let queryStr = '';
      
      if (cleanUrl.includes('?')) {
        queryStr = cleanUrl.split('?')[1];
      } else {
        queryStr = cleanUrl;
      }

      const parsedParams = {};
      queryStr.split('&').forEach(part => {
        const item = part.split('=');
        if (item.length === 2) {
          parsedParams[item[0]] = item[1];
        }
      });

      if (parsedParams.requestId && parsedParams.token) {
        setRequestId(parsedParams.requestId);
        setToken(parsedParams.token);
        setStatus('ready');
        setCountdown(120);
      } else {
        Alert.alert('Invalid URL', 'Could not find requestId or token in the provided link.');
      }
    } catch (err) {
      Alert.alert('Error', 'Failed to parse link: ' + err.message);
    }
  };

  // Countdown timer
  useEffect(() => {
    if (status !== 'ready') return;
    
    const interval = setInterval(() => {
      setCountdown(prev => {
        if (prev <= 1) {
          clearInterval(interval);
          setStatus('expired');
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(interval);
  }, [status]);

  const handleAction = async (action) => {
    setStatus('loading');
    setError('');
    try {
      await respondToPushLogin(requestId, token, action);
      setStatus(action === 'approve' ? 'approved' : 'denied');
      
      if (action === 'approve') {
        setTimeout(() => navigate('Dashboard'), 2000);
      }
    } catch (err) {
      const msg = err?.response?.data?.error || err?.message || 'Something went wrong';
      if (msg.includes('expired')) {
        setStatus('expired');
      } else {
        setStatus('error');
        setError(msg);
      }
    }
  };

  return (
    <ScrollView contentContainerStyle={[styles.container, { backgroundColor: colors.bg }]}>
      {/* Back to Dashboard header link */}
      <TouchableOpacity style={styles.backRow} onPress={() => navigate('Dashboard')}>
        <ArrowLeft size={16} color={colors.textSecondary} />
        <Text style={[styles.backText, { color: colors.textSecondary }]}>Back to Dashboard</Text>
      </TouchableOpacity>

      <View style={[styles.card, { backgroundColor: colors.bgCard, borderColor: colors.border }]}>
        
        {/* Input Paste Link view */}
        {status === 'input' && (
          <View style={styles.stateWrapper}>
            <View style={[styles.iconWrap, { backgroundColor: colors.primaryLight }]}>
              <Smartphone size={32} color={colors.primary} />
            </View>
            <Text style={[styles.title, { color: colors.text }]}>MFA Push Authenticator</Text>
            <Text style={[styles.desc, { color: colors.textSecondary }]}>
              Paste the approval link generated by the web application sign-in page to allow access.
            </Text>

            <TextInput
              style={[styles.inputUrl, { color: colors.text, borderColor: colors.border, backgroundColor: colors.bg }]}
              placeholder="Paste login request link here..."
              placeholderTextColor={colors.textMuted}
              value={inputUrl}
              onChangeText={setInputUrl}
              autoCapitalize="none"
              multiline
            />

            <TouchableOpacity 
              style={[styles.btn, { backgroundColor: colors.primary }]}
              onPress={handleParseUrl}
            >
              <Text style={styles.btnText}>Parse Link</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* Ready review view */}
        {status === 'ready' && (
          <View style={styles.stateWrapper}>
            <View style={[styles.iconCircle, { backgroundColor: '#fff7e6', borderColor: '#ddd5c3' }]}>
              <KeyRound size={32} color="#b8963e" />
            </View>
            <Text style={[styles.title, { color: colors.text }]}>Login Request</Text>
            <Text style={[styles.desc, { color: colors.textSecondary }]}>
              Someone is trying to sign in to your <Text style={{ fontWeight: '700', color: colors.text }}>Hi</Text> account. Do you want to allow this?
            </Text>

            <View style={[styles.timerBox, { backgroundColor: colors.bg }]}>
              <Text style={[styles.timerVal, { color: '#b8963e', textAlign: 'center', width: '100%' }]}>
                This request expires in {Math.floor(countdown / 60)}:{String(countdown % 60).padStart(2, '0')}
              </Text>
            </View>

            <View style={styles.actionRow}>
              <TouchableOpacity 
                style={[styles.actionBtn, { borderColor: colors.accentRed, borderWidth: 1.5 }]} 
                onPress={() => handleAction('deny')}
              >
                <Text style={[styles.actionBtnText, { color: colors.accentRed }]}>Deny</Text>
              </TouchableOpacity>

              <TouchableOpacity 
                style={[styles.actionBtn, { backgroundColor: colors.success || '#2d6a4f' }]} 
                onPress={() => handleAction('approve')}
              >
                <Text style={[styles.actionBtnText, { color: '#fff' }]}>Approve</Text>
              </TouchableOpacity>
            </View>
          </View>
        )}

        {/* Loading Spinner */}
        {status === 'loading' && (
          <View style={styles.stateWrapper}>
            <ActivityIndicator size="large" color={colors.primary} />
            <Text style={[styles.statusInfoText, { color: colors.textSecondary, marginTop: 16 }]}>
              Processing your request...
            </Text>
          </View>
        )}

        {/* Approved Success State */}
        {status === 'approved' && (
          <View style={styles.stateWrapper}>
            <View style={[styles.iconCircle, { backgroundColor: '#d4edda', borderColor: '#b7e4c7' }]}>
              <Check size={36} color="#2d6a4f" />
            </View>
            <Text style={[styles.title, { color: colors.success || '#2d6a4f' }]}>Login Approved!</Text>
            <Text style={[styles.desc, { color: colors.textSecondary }]}>
              The requesting device has been signed in successfully. You can close this screen.
            </Text>
          </View>
        )}

        {/* Denied State */}
        {status === 'denied' && (
          <View style={styles.stateWrapper}>
            <View style={[styles.iconCircle, { backgroundColor: '#fef2f2', borderColor: '#fecaca' }]}>
              <X size={36} color={colors.accentRed} />
            </View>
            <Text style={[styles.title, { color: colors.accentRed }]}>Login Denied</Text>
            <Text style={[styles.desc, { color: colors.textSecondary }]}>
              The login attempt has been blocked. If this wasn't you, your account is safe. You can close this screen.
            </Text>
            <TouchableOpacity style={[styles.btn, { backgroundColor: colors.primary, marginTop: 24 }]} onPress={() => setStatus('input')}>
              <Text style={styles.btnText}>Back</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* Expired State */}
        {status === 'expired' && (
          <View style={styles.stateWrapper}>
            <View style={[styles.iconCircle, { backgroundColor: '#fff7e6', borderColor: '#f0e6c8' }]}>
              <ShieldAlert size={36} color="#b8963e" />
            </View>
            <Text style={[styles.title, { color: '#b8963e' }]}>Request Expired</Text>
            <Text style={[styles.desc, { color: colors.textSecondary }]}>
              This login request has expired. Please try again from the login page.
            </Text>
            <TouchableOpacity style={[styles.btn, { backgroundColor: colors.primary, marginTop: 24 }]} onPress={() => setStatus('input')}>
              <Text style={styles.btnText}>Try Another</Text>
            </TouchableOpacity>
          </View>
        )}

        {/* Error State */}
        {status === 'error' && (
          <View style={styles.stateWrapper}>
            <View style={[styles.iconCircle, { backgroundColor: '#fef2f2', borderColor: '#fecaca' }]}>
              <ShieldAlert size={36} color={colors.accentRed} />
            </View>
            <Text style={[styles.title, { color: colors.text }]}>Something went wrong</Text>
            <Text style={[styles.desc, { color: colors.textSecondary }]}>{error || 'Invalid request. Please try again.'}</Text>
            <TouchableOpacity style={[styles.btn, { backgroundColor: colors.primary, marginTop: 24 }]} onPress={() => setStatus('input')}>
              <Text style={styles.btnText}>Try Again</Text>
            </TouchableOpacity>
          </View>
        )}

      </View>

      {/* Security notice matching web */}
      <Text style={[styles.securityNotice, { color: colors.textMuted }]}>
        This request is secured with a unique cryptographic token.{"\n"}
        Never approve a login you didn't initiate.
      </Text>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    padding: 24,
    paddingTop: 56,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    marginBottom: 20,
    width: '100%',
    maxWidth: 400,
  },
  backText: {
    fontSize: 13,
    fontWeight: '600',
  },
  card: {
    width: '100%',
    maxWidth: 400,
    borderRadius: 24,
    borderWidth: 1,
    padding: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  stateWrapper: {
    alignItems: 'center',
    width: '100%',
  },
  iconWrap: {
    width: 64,
    height: 64,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  iconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  title: {
    fontSize: 22,
    fontFamily: 'Georgia',
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 12,
  },
  desc: {
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 1.8,
    marginBottom: 24,
  },
  inputUrl: {
    width: '100%',
    borderWidth: 1.5,
    borderRadius: 12,
    minHeight: 64,
    padding: 12,
    fontSize: 13,
    marginBottom: 20,
    textAlignVertical: 'top',
  },
  btn: {
    height: 48,
    borderRadius: 12,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  timerBox: {
    width: '100%',
    padding: 14,
    borderRadius: 12,
    marginBottom: 24,
    backgroundColor: '#f5f0e8',
  },
  timerVal: {
    fontSize: 12,
    fontWeight: '700',
  },
  actionRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  actionBtn: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBtnText: {
    fontSize: 14,
    fontWeight: '700',
  },
  statusInfoText: {
    fontSize: 13,
  },
  securityNotice: {
    textAlign: 'center',
    fontSize: 11,
    marginTop: 24,
    lineHeight: 1.6,
    maxWidth: 280,
  },
});
